<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17745" started-at="2023-03-22T16:00:16Z" finished-at="2023-03-22T16:00:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="17745" started-at="2023-03-22T16:00:16Z" finished-at="2023-03-22T16:00:34Z">
      <class name="com.test.HomePageTest">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:com.test.HomePageTest@13805618]" name="launchBrowser" is-config="true" duration-ms="4828" started-at="2023-03-22T21:30:16Z" finished-at="2023-03-22T21:30:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="preRun()[pri:0, instance:com.test.HomePageTest@13805618]" name="preRun" is-config="true" duration-ms="12550" started-at="2023-03-22T21:30:21Z" finished-at="2023-03-22T21:30:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preRun -->
        <test-method status="FAIL" signature="validateHomePageFields()[pri:1, instance:com.test.HomePageTest@13805618]" name="validateHomePageFields" duration-ms="86" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Failure message:Reparation field not displayed expected [true] but found [false],
	Failure message:Client field not displayed expected [true] but found [false],
	Failure message:Products field not displayed expected [true] but found [false],
	Failure message:Calendar not displayed expected [true] but found [false],
	Failure message:Revenue chart field not displayed expected [true] but found [false],
	Failure message:Stock chart field not displayed expected [true] but found [false],
	Failure message:Quick Email field not displayed expected [true] but found [false],
	Failure message:Quick SMS field not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Failure message:Reparation field not displayed expected [true] but found [false],
	Failure message:Client field not displayed expected [true] but found [false],
	Failure message:Products field not displayed expected [true] but found [false],
	Failure message:Calendar not displayed expected [true] but found [false],
	Failure message:Revenue chart field not displayed expected [true] but found [false],
	Failure message:Stock chart field not displayed expected [true] but found [false],
	Failure message:Quick Email field not displayed expected [true] but found [false],
	Failure message:Quick SMS field not displayed expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.test.HomePageTest.validateHomePageFields(HomePageTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageFields -->
        <test-method status="PASS" signature="preRun()[pri:0, instance:com.test.HomePageTest@13805618]" name="preRun" is-config="true" duration-ms="33" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preRun -->
        <test-method status="FAIL" signature="validateHomePageTopPanelFields()[pri:2, instance:com.test.HomePageTest@13805618]" name="validateHomePageTopPanelFields" duration-ms="61" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Failure message:Service Management Text not displayed expected [true] but found [false],
	Failure message:Side-Bar toggle button not displayed expected [true] but found [false],
	Failure message:Alert Button not displayed expected [true] but found [false],
	Failure message:Add Button not displayed expected [true] but found [false],
	Failure message:Logged-in username not displayed expected [true] but found [false],
	Failure message:Number of alerts not displayed expected [true] but found [false],
	Failure message:Add Button not clicked expected [true] but found [false],
	Failure message:Add Client Button not displayed expected [true] but found [false],
	Failure message:Add Reparation Button not displayed expected [true] but found [false],
	Failure message:Send SMS Button not displayed expected [true] but found [false],
	Failure message:Send Email Button not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Failure message:Service Management Text not displayed expected [true] but found [false],
	Failure message:Side-Bar toggle button not displayed expected [true] but found [false],
	Failure message:Alert Button not displayed expected [true] but found [false],
	Failure message:Add Button not displayed expected [true] but found [false],
	Failure message:Logged-in username not displayed expected [true] but found [false],
	Failure message:Number of alerts not displayed expected [true] but found [false],
	Failure message:Add Button not clicked expected [true] but found [false],
	Failure message:Add Client Button not displayed expected [true] but found [false],
	Failure message:Add Reparation Button not displayed expected [true] but found [false],
	Failure message:Send SMS Button not displayed expected [true] but found [false],
	Failure message:Send Email Button not displayed expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.test.HomePageTest.validateHomePageTopPanelFields(HomePageTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageTopPanelFields -->
        <test-method status="PASS" signature="preRun()[pri:0, instance:com.test.HomePageTest@13805618]" name="preRun" is-config="true" duration-ms="23" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preRun -->
        <test-method status="FAIL" signature="validateHomePageLeftPanelFields()[pri:3, instance:com.test.HomePageTest@13805618]" name="validateHomePageLeftPanelFields" duration-ms="42" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Failure message:Logged in username not displayed in left panel expected [true] but found [false],
	Failure message:Search reparations textbox not displayed expected [true] but found [false],
	Failure message:Main Navigation text missing in left panel expected [true] but found [false],
	Failure message:Home button not displayed in left panel expected [true] but found [false],
	Failure message: Settings button not displayed in left panel expected [true] but found [false],
	Failure message:Settings options missing in left panel expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Failure message:Logged in username not displayed in left panel expected [true] but found [false],
	Failure message:Search reparations textbox not displayed expected [true] but found [false],
	Failure message:Main Navigation text missing in left panel expected [true] but found [false],
	Failure message:Home button not displayed in left panel expected [true] but found [false],
	Failure message: Settings button not displayed in left panel expected [true] but found [false],
	Failure message:Settings options missing in left panel expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.test.HomePageTest.validateHomePageLeftPanelFields(HomePageTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageLeftPanelFields -->
        <test-method status="PASS" signature="preRun()[pri:0, instance:com.test.HomePageTest@13805618]" name="preRun" is-config="true" duration-ms="19" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preRun -->
        <test-method status="FAIL" signature="validateQuickEmailAndQuickSmsOption()[pri:4, instance:com.test.HomePageTest@13805618]" name="validateQuickEmailAndQuickSmsOption" duration-ms="63" started-at="2023-03-22T21:30:34Z" finished-at="2023-03-22T21:30:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Failure message:Please enter emailid expected [true] but found [false],
	Failure message:Please enter mail subject expected [true] but found [false],
	Failure message:Please enter mail body expected [true] but found [false],
	Failure message:Email not send expected [true] but found [false],
	Failure message:Please enter mobile number expected [true] but found [false],
	Failure message:Please enter SMS message expected [true] but found [false],
	Failure message:SMS not send expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Failure message:Please enter emailid expected [true] but found [false],
	Failure message:Please enter mail subject expected [true] but found [false],
	Failure message:Please enter mail body expected [true] but found [false],
	Failure message:Email not send expected [true] but found [false],
	Failure message:Please enter mobile number expected [true] but found [false],
	Failure message:Please enter SMS message expected [true] but found [false],
	Failure message:SMS not send expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.test.HomePageTest.validateQuickEmailAndQuickSmsOption(HomePageTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateQuickEmailAndQuickSmsOption -->
      </class> <!-- com.test.HomePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
